import type {
  Blueprint,
  ProjectTemplate,
  RequirementsModel,
  ScaffoldContext,
  TemplateMatch,
  VirtualFile,
} from '@calecosystem/contracts';
import { fileFactory } from '../scaffold/shared.ts';
import { scoreTemplate } from './detect.ts';
import { addEndpoints, addPages, ensureEntity, recordTemplateDecision } from './shared.ts';

const TOOL = 'calec.template.ecommerce';
const file = fileFactory(TOOL);

/**
 * Plantilla de comercio electronico.
 *
 * Aporta lo que ninguna tienda puede no tener y que un CRUD generico nunca
 * deduce: carrito con persistencia local, proceso de compra y panel de
 * pedidos. El catalogo si sale del analisis, porque los productos varian de
 * un negocio a otro y la plantilla no debe imponer su modelo.
 */
export const ecommerceTemplate: ProjectTemplate = {
  id: 'calec.template.ecommerce',
  name: 'E-commerce',
  description: 'Catalogo, carrito, proceso de compra y panel de pedidos.',
  kind: 'ecommerce',
  tier: 'community',
  frameworks: ['react'],

  detect(requirements: RequirementsModel): TemplateMatch {
    return scoreTemplate(requirements, {
      signals: [
        'tienda', 'ecommerce', 'e-commerce', 'comercio electronico', 'carrito',
        'checkout', 'marketplace', 'catalogo', 'vender', 'venta', 'compra',
        'comprar', 'pedidos', 'envio', 'stock',
      ],
      entities: ['Product', 'Order', 'Cart', 'Customer'],
      features: ['payments'],
      // Un panel interno gestiona pedidos y productos, pero no es una tienda:
      // generarle un carrito y un proceso de compra es ruido, no valor.
      antiSignals: [
        'landing', 'captacion de leads', 'panel interno', 'uso interno',
        'empleados', 'backoffice', 'back office', 'herramienta interna',
      ],
    });
  },

  refine(blueprint: Blueprint): Blueprint {
    let refined = ensureEntity(blueprint, 'Product');
    refined = ensureEntity(refined, 'Order');
    refined = ensureEntity(refined, 'Customer');
    refined = ensureEntity(refined, 'CartItem', [
      { name: 'id', type: 'uuid', required: true },
      { name: 'productId', type: 'reference', required: true, references: 'Product' },
      { name: 'quantity', type: 'number', required: true },
      { name: 'unitPrice', type: 'decimal', required: true },
      { name: 'createdAt', type: 'datetime', required: true },
      { name: 'updatedAt', type: 'datetime', required: true },
    ]);

    refined = addPages(refined, [
      { route: '/catalog', name: 'Catalog', kind: 'list', entity: 'Product', requiresAuth: false },
      { route: '/cart', name: 'Cart', kind: 'detail', entity: 'CartItem', requiresAuth: false },
      { route: '/checkout', name: 'Checkout', kind: 'form', entity: 'Order', requiresAuth: false },
      { route: '/admin/orders', name: 'AdminOrders', kind: 'dashboard', entity: 'Order', requiresAuth: true },
      { route: '/admin/products', name: 'AdminProducts', kind: 'dashboard', entity: 'Product', requiresAuth: true },
    ]);

    refined = addEndpoints(refined, [
      {
        method: 'POST',
        path: '/api/checkout',
        summary: 'Confirma el carrito y crea el pedido',
        entity: 'Order',
        requiresAuth: false,
      },
      {
        method: 'GET',
        path: '/api/catalog',
        summary: 'Catalogo publico con filtros y paginacion',
        entity: 'Product',
        requiresAuth: false,
      },
    ]);

    // El inventario es la fuente numero uno de incidencias en una tienda:
    // dos clientes comprando la ultima unidad a la vez.
    refined = {
      ...refined,
      risks: [
        ...refined.risks,
        {
          id: 'RISK-STOCK-RACE',
          title: 'Condicion de carrera al descontar stock',
          impact: 'high',
          mitigation:
            'Descontar existencias dentro de la misma transaccion que crea el pedido, con bloqueo por fila.',
          owner: 'tester',
        },
      ],
    };

    return recordTemplateDecision(refined, 'E-commerce', 'carrito, proceso de compra y panel de pedidos');
  },

  scaffold({ blueprint, dependencies }: ScaffoldContext): VirtualFile[] {
    const root = 'apps/web/src';

    dependencies.contribute({
      workspace: 'web',
      requestedBy: TOOL,
      scripts: { 'test:e2e': 'echo "Anade aqui tu runner de e2e"' },
    });

    return [
      file(`${root}/features/cart/CartContext.tsx`, cartContext(blueprint.slug)),
      file(`${root}/features/cart/useCart.ts`, useCartHook()),
      file(`${root}/features/catalog/ProductGrid.tsx`, productGrid()),
      file(`${root}/pages/CatalogPage.tsx`, catalogPage()),
      file(`${root}/pages/CartPage.tsx`, cartPage()),
      file(`${root}/pages/CheckoutPage.tsx`, checkoutPage()),
      file(`${root}/pages/AdminOrdersPage.tsx`, adminOrdersPage()),
      file('apps/api/src/routes/checkout.routes.ts', checkoutRoutes()),
      file('apps/api/src/application/CheckoutService.ts', checkoutService()),
      // Nombre deliberado: son las reglas de precio del carrito, no la
      // entidad `Cart` que el analizador ya pudo deducir del enunciado.
      file('apps/api/src/domain/CartPricing.ts', cartDomain()),
      file('apps/api/src/domain/CartPricing.test.ts', cartDomainTest()),
    ];
  },
};

function cartContext(slug: string): string {
  return [
    '/**',
    ' * Estado del carrito.',
    ' *',
    ' * Se guarda en `localStorage` porque un carrito que se vacia al recargar',
    ' * pierde ventas. El precio se recalcula SIEMPRE en el servidor al pagar:',
    ' * lo que hay aqui es una copia de conveniencia para pintar la interfaz.',
    ' */',
    "import { createContext, useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';",
    "import type { Product } from '../../types.ts';",
    '',
    'export interface CartLine {',
    '  productId: string;',
    '  name: string;',
    '  unitPrice: number;',
    '  quantity: number;',
    '}',
    '',
    'export interface CartState {',
    '  lines: CartLine[];',
    '  add(product: Product, quantity?: number): void;',
    '  remove(productId: string): void;',
    '  setQuantity(productId: string, quantity: number): void;',
    '  clear(): void;',
    '  itemCount: number;',
    '  subtotal: number;',
    '}',
    '',
    'export const CartContext = createContext<CartState | null>(null);',
    '',
    `const STORAGE_KEY = '${slug}.cart';`,
    '',
    'function readStoredLines(): CartLine[] {',
    '  try {',
    '    const raw = localStorage.getItem(STORAGE_KEY);',
    '    return raw ? (JSON.parse(raw) as CartLine[]) : [];',
    '  } catch {',
    '    // Almacenamiento no disponible o corrupto: arrancar vacio es',
    '    // preferible a romper la aplicacion entera.',
    '    return [];',
    '  }',
    '}',
    '',
    'export function CartProvider({ children }: { children: ReactNode }) {',
    '  const [lines, setLines] = useState<CartLine[]>(readStoredLines);',
    '',
    '  useEffect(() => {',
    '    try {',
    '      localStorage.setItem(STORAGE_KEY, JSON.stringify(lines));',
    '    } catch {',
    '      // Modo privado o cuota agotada: no es motivo para perder el carrito',
    '      // de esta sesion.',
    '    }',
    '  }, [lines]);',
    '',
    '  const add = useCallback((product: Product, quantity = 1) => {',
    '    setLines((current) => {',
    '      const existing = current.find((line) => line.productId === product.id);',
    '      if (existing) {',
    '        return current.map((line) =>',
    '          line.productId === product.id',
    '            ? { ...line, quantity: line.quantity + quantity }',
    '            : line,',
    '        );',
    '      }',
    '      return [',
    '        ...current,',
    '        {',
    '          productId: product.id,',
    '          name: product.name,',
    '          unitPrice: Number(product.price),',
    '          quantity,',
    '        },',
    '      ];',
    '    });',
    '  }, []);',
    '',
    '  const remove = useCallback((productId: string) => {',
    '    setLines((current) => current.filter((line) => line.productId !== productId));',
    '  }, []);',
    '',
    '  const setQuantity = useCallback((productId: string, quantity: number) => {',
    '    // Cantidad cero equivale a eliminar: evita lineas fantasma en el carrito.',
    '    if (quantity <= 0) {',
    '      setLines((current) => current.filter((line) => line.productId !== productId));',
    '      return;',
    '    }',
    '    setLines((current) =>',
    '      current.map((line) => (line.productId === productId ? { ...line, quantity } : line)),',
    '    );',
    '  }, []);',
    '',
    '  const clear = useCallback(() => setLines([]), []);',
    '',
    '  const value = useMemo<CartState>(() => {',
    '    const itemCount = lines.reduce((total, line) => total + line.quantity, 0);',
    '    const subtotal = lines.reduce((total, line) => total + line.unitPrice * line.quantity, 0);',
    '    return { lines, add, remove, setQuantity, clear, itemCount, subtotal };',
    '  }, [lines, add, remove, setQuantity, clear]);',
    '',
    '  return <CartContext.Provider value={value}>{children}</CartContext.Provider>;',
    '}',
  ].join('\n');
}

function useCartHook(): string {
  return [
    "import { useContext } from 'react';",
    "import { CartContext, type CartState } from './CartContext.tsx';",
    '',
    '/** Acceso al carrito. Falla pronto si falta el proveedor. */',
    'export function useCart(): CartState {',
    '  const context = useContext(CartContext);',
    '  if (!context) {',
    "    throw new Error('useCart debe usarse dentro de <CartProvider>.');",
    '  }',
    '  return context;',
    '}',
  ].join('\n');
}

function productGrid(): string {
  return [
    "import { Button } from '../../components/ui/Button.tsx';",
    "import { Card } from '../../components/ui/Card.tsx';",
    "import { useCart } from '../cart/useCart.ts';",
    "import type { Product } from '../../types.ts';",
    '',
    'export interface ProductGridProps {',
    '  products: readonly Product[];',
    '}',
    '',
    '/** Rejilla de catalogo. Anadir al carrito no navega: la compra sigue abierta. */',
    'export function ProductGrid({ products }: ProductGridProps) {',
    '  const cart = useCart();',
    '',
    '  return (',
    '    <ul className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">',
    '      {products.map((product) => (',
    '        <li key={product.id}>',
    '          <Card title={product.name}>',
    '            <p className="mb-2 text-sm text-slate-600">{product.description}</p>',
    '            <p className="mb-3 text-lg font-semibold">',
    "              {new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(",
    '                Number(product.price),',
    '              )}',
    '            </p>',
    '            <Button onClick={() => cart.add(product)} disabled={Number(product.stock) <= 0}>',
    "              {Number(product.stock) > 0 ? 'Anadir al carrito' : 'Sin existencias'}",
    '            </Button>',
    '          </Card>',
    '        </li>',
    '      ))}',
    '    </ul>',
    '  );',
    '}',
  ].join('\n');
}

function catalogPage(): string {
  return [
    "import { useEffect, useState } from 'react';",
    "import { apiFetch } from '../api/client.ts';",
    "import { ProductGrid } from '../features/catalog/ProductGrid.tsx';",
    "import { Spinner } from '../components/ui/Spinner.tsx';",
    "import { Alert } from '../components/ui/Alert.tsx';",
    "import type { Product } from '../types.ts';",
    '',
    'export function CatalogPage() {',
    '  const [products, setProducts] = useState<Product[]>([]);',
    '  const [error, setError] = useState<string | null>(null);',
    '  const [loading, setLoading] = useState(true);',
    '',
    '  useEffect(() => {',
    '    let cancelled = false;',
    "    apiFetch<Product[]>('/catalog')",
    '      .then((data) => !cancelled && setProducts(data))',
    '      .catch((cause: unknown) => !cancelled && setError(String(cause)))',
    '      .finally(() => !cancelled && setLoading(false));',
    '    return () => {',
    '      cancelled = true;',
    '    };',
    '  }, []);',
    '',
    '  if (loading) return <Spinner label="Cargando catalogo" />;',
    '  if (error) return <Alert tone="error">{error}</Alert>;',
    '',
    '  return (',
    '    <section>',
    '      <h1 className="mb-4 text-xl font-semibold">Catalogo</h1>',
    '      <ProductGrid products={products} />',
    '    </section>',
    '  );',
    '}',
  ].join('\n');
}

function cartPage(): string {
  return [
    "import { Link } from 'react-router-dom';",
    "import { Button } from '../components/ui/Button.tsx';",
    "import { EmptyState } from '../components/ui/EmptyState.tsx';",
    "import { useCart } from '../features/cart/useCart.ts';",
    '',
    "const currency = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' });",
    '',
    'export function CartPage() {',
    '  const cart = useCart();',
    '',
    '  if (cart.lines.length === 0) {',
    '    return (',
    '      <EmptyState',
    '        title="Tu carrito esta vacio"',
    '        description="Anade productos desde el catalogo para continuar."',
    '        action={<Link to="/catalog">Ver catalogo</Link>}',
    '      />',
    '    );',
    '  }',
    '',
    '  return (',
    '    <section>',
    '      <h1 className="mb-4 text-xl font-semibold">Tu carrito</h1>',
    '      <ul className="flex flex-col gap-3">',
    '        {cart.lines.map((line) => (',
    '          <li key={line.productId} className="flex items-center justify-between gap-4 border-b py-2">',
    '            <span>{line.name}</span>',
    '            <input',
    '              type="number"',
    '              min={0}',
    '              value={line.quantity}',
    '              aria-label={`Cantidad de ${line.name}`}',
    '              onChange={(event) => cart.setQuantity(line.productId, Number(event.target.value))}',
    '              className="w-20 rounded border px-2 py-1"',
    '            />',
    '            <span>{currency.format(line.unitPrice * line.quantity)}</span>',
    '            <Button variant="ghost" onClick={() => cart.remove(line.productId)}>',
    '              Quitar',
    '            </Button>',
    '          </li>',
    '        ))}',
    '      </ul>',
    '      <p className="mt-4 text-right text-lg font-semibold">',
    '        Subtotal: {currency.format(cart.subtotal)}',
    '      </p>',
    '      <div className="mt-4 text-right">',
    '        <Link to="/checkout">',
    '          <Button>Finalizar compra</Button>',
    '        </Link>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
  ].join('\n');
}

function checkoutPage(): string {
  return [
    "import { useState } from 'react';",
    "import { useNavigate } from 'react-router-dom';",
    "import { apiFetch } from '../api/client.ts';",
    "import { Alert } from '../components/ui/Alert.tsx';",
    "import { Button } from '../components/ui/Button.tsx';",
    "import { Input } from '../components/ui/Input.tsx';",
    "import { useCart } from '../features/cart/useCart.ts';",
    '',
    'interface CheckoutResponse {',
    '  orderId: string;',
    '  total: number;',
    '}',
    '',
    'export function CheckoutPage() {',
    '  const cart = useCart();',
    '  const navigate = useNavigate();',
    "  const [email, setEmail] = useState('');",
    "  const [fullName, setFullName] = useState('');",
    '  const [error, setError] = useState<string | null>(null);',
    '  const [submitting, setSubmitting] = useState(false);',
    '',
    '  const submit = async (event: React.FormEvent) => {',
    '    event.preventDefault();',
    '    setSubmitting(true);',
    '    setError(null);',
    '    try {',
    '      // Solo se envian identificadores y cantidades: el precio lo pone el',
    '      // servidor. Confiar en el importe del cliente es como se regalan',
    '      // productos sin querer.',
    "      const response = await apiFetch<CheckoutResponse>('/checkout', {",
    "        method: 'POST',",
    '        body: JSON.stringify({',
    '          customer: { email, fullName },',
    '          lines: cart.lines.map((line) => ({',
    '            productId: line.productId,',
    '            quantity: line.quantity,',
    '          })),',
    '        }),',
    '      });',
    '      cart.clear();',
    '      navigate(`/orders/${response.orderId}`);',
    '    } catch (cause) {',
    '      setError(cause instanceof Error ? cause.message : String(cause));',
    '    } finally {',
    '      setSubmitting(false);',
    '    }',
    '  };',
    '',
    '  return (',
    '    <form onSubmit={submit} className="flex max-w-md flex-col gap-4">',
    '      <h1 className="text-xl font-semibold">Finalizar compra</h1>',
    '      {error && <Alert tone="error">{error}</Alert>}',
    '      <Input id="checkout-name" label="Nombre completo" value={fullName} required onChange={setFullName} />',
    '      <Input id="checkout-email" label="Email" type="email" value={email} required onChange={setEmail} />',
    '      <Button type="submit" loading={submitting} disabled={cart.lines.length === 0}>',
    '        Pagar',
    '      </Button>',
    '    </form>',
    '  );',
    '}',
  ].join('\n');
}

function adminOrdersPage(): string {
  return [
    "import { useEffect, useState } from 'react';",
    "import { apiFetch } from '../api/client.ts';",
    "import { Badge } from '../components/ui/Badge.tsx';",
    "import { DataTable } from '../components/ui/DataTable.tsx';",
    "import type { Order } from '../types.ts';",
    '',
    'const columns = [',
    "  { key: 'reference', header: 'Referencia' },",
    "  { key: 'status', header: 'Estado' },",
    "  { key: 'total', header: 'Total' },",
    "  { key: 'placedAt', header: 'Fecha' },",
    '];',
    '',
    'export function AdminOrdersPage() {',
    '  const [orders, setOrders] = useState<Order[]>([]);',
    '  const [loading, setLoading] = useState(true);',
    '',
    '  useEffect(() => {',
    "    apiFetch<Order[]>('/orders')",
    '      .then(setOrders)',
    '      .finally(() => setLoading(false));',
    '  }, []);',
    '',
    '  const pending = orders.filter((order) => order.status === \'pending\').length;',
    '',
    '  return (',
    '    <section>',
    '      <header className="mb-4 flex items-center gap-3">',
    '        <h1 className="text-xl font-semibold">Pedidos</h1>',
    '        <Badge tone={pending > 0 ? \'warning\' : \'success\'}>{pending} pendientes</Badge>',
    '      </header>',
    '      <DataTable',
    '        columns={columns}',
    '        rows={orders as readonly Record<string, unknown>[]}',
    '        loading={loading}',
    '        emptyMessage="Todavia no hay pedidos."',
    '      />',
    '    </section>',
    '  );',
    '}',
  ].join('\n');
}

function cartDomain(): string {
  return [
    '/**',
    ' * Reglas del carrito, en el dominio y sin dependencias.',
    ' *',
    ' * Estan aqui y no en la ruta HTTP porque son las reglas que mas veces se',
    ' * tocan y las que mas caro sale equivocar: un redondeo mal hecho es dinero.',
    ' */',
    '',
    'export interface CartLineInput {',
    '  productId: string;',
    '  quantity: number;',
    '}',
    '',
    'export interface PricedLine {',
    '  productId: string;',
    '  quantity: number;',
    '  unitPrice: number;',
    '  lineTotal: number;',
    '}',
    '',
    'export interface CartTotals {',
    '  subtotal: number;',
    '  tax: number;',
    '  total: number;',
    '}',
    '',
    'export const DEFAULT_TAX_RATE = 0.21;',
    '',
    '/** Redondeo a centimos. Sin esto, 0.1 + 0.2 acaba en la factura. */',
    'export function roundCents(value: number): number {',
    '  return Math.round(value * 100) / 100;',
    '}',
    '',
    'export function priceLines(',
    '  lines: readonly CartLineInput[],',
    '  priceOf: (productId: string) => number | undefined,',
    '): PricedLine[] {',
    '  return lines.map((line) => {',
    '    const unitPrice = priceOf(line.productId);',
    '    if (unitPrice === undefined) {',
    "      throw new Error('Producto no encontrado: ' + line.productId);",
    '    }',
    '    if (!Number.isInteger(line.quantity) || line.quantity <= 0) {',
    "      throw new Error('Cantidad no valida para ' + line.productId);",
    '    }',
    '    return {',
    '      productId: line.productId,',
    '      quantity: line.quantity,',
    '      unitPrice,',
    '      lineTotal: roundCents(unitPrice * line.quantity),',
    '    };',
    '  });',
    '}',
    '',
    'export function calculateTotals(',
    '  lines: readonly PricedLine[],',
    '  taxRate: number = DEFAULT_TAX_RATE,',
    '): CartTotals {',
    '  const subtotal = roundCents(lines.reduce((sum, line) => sum + line.lineTotal, 0));',
    '  const tax = roundCents(subtotal * taxRate);',
    '  return { subtotal, tax, total: roundCents(subtotal + tax) };',
    '}',
  ].join('\n');
}

function cartDomainTest(): string {
  return [
    "import test from 'node:test';",
    "import assert from 'node:assert/strict';",
    "import { calculateTotals, priceLines, roundCents } from './CartPricing.ts';",
    '',
    "const prices: Record<string, number> = { 'p-1': 19.99, 'p-2': 5.5 };",
    'const priceOf = (id: string) => prices[id];',
    '',
    "test('calcula el total de cada linea', () => {",
    "  const lines = priceLines([{ productId: 'p-1', quantity: 3 }], priceOf);",
    '  assert.equal(lines[0]?.lineTotal, 59.97);',
    '});',
    '',
    "test('rechaza cantidades no validas', () => {",
    "  assert.throws(() => priceLines([{ productId: 'p-1', quantity: 0 }], priceOf), /Cantidad/);",
    "  assert.throws(() => priceLines([{ productId: 'p-1', quantity: 1.5 }], priceOf), /Cantidad/);",
    '});',
    '',
    "test('rechaza productos inexistentes', () => {",
    "  assert.throws(() => priceLines([{ productId: 'nope', quantity: 1 }], priceOf), /no encontrado/);",
    '});',
    '',
    "test('aplica impuestos sobre el subtotal redondeado', () => {",
    '  const lines = priceLines(',
    "    [{ productId: 'p-1', quantity: 1 }, { productId: 'p-2', quantity: 2 }],",
    '    priceOf,',
    '  );',
    '  const totals = calculateTotals(lines);',
    '  assert.equal(totals.subtotal, 30.99);',
    '  assert.equal(totals.tax, 6.51);',
    '  assert.equal(totals.total, 37.5);',
    '});',
    '',
    "test('el redondeo evita los errores de coma flotante', () => {",
    '  assert.equal(roundCents(0.1 + 0.2), 0.3);',
    '});',
  ].join('\n');
}

function checkoutService(): string {
  return [
    "import { calculateTotals, priceLines, type CartLineInput } from '../domain/CartPricing.ts';",
    '',
    'export interface CheckoutInput {',
    '  customer: { email: string; fullName: string };',
    '  lines: readonly CartLineInput[];',
    '}',
    '',
    'export interface CheckoutResult {',
    '  orderId: string;',
    '  total: number;',
    '}',
    '',
    'export interface ProductPriceSource {',
    '  priceOf(productId: string): number | undefined;',
    '  reserveStock(productId: string, quantity: number): Promise<boolean>;',
    '}',
    '',
    '/**',
    ' * Proceso de compra.',
    ' *',
    ' * Recalcula precios en el servidor y reserva existencias antes de crear el',
    ' * pedido. PENDIENTE: envolver reserva y creacion en una unica transaccion',
    ' * al conectar la base de datos real; ver RISK-STOCK-RACE en el blueprint.',
    ' */',
    'export class CheckoutService {',
    '  readonly #products: ProductPriceSource;',
    '  readonly #createOrder: (input: { email: string; total: number }) => Promise<string>;',
    '',
    '  constructor(',
    '    products: ProductPriceSource,',
    '    createOrder: (input: { email: string; total: number }) => Promise<string>,',
    '  ) {',
    '    this.#products = products;',
    '    this.#createOrder = createOrder;',
    '  }',
    '',
    '  async checkout(input: CheckoutInput): Promise<CheckoutResult> {',
    '    if (input.lines.length === 0) {',
    "      throw new Error('El carrito esta vacio');",
    '    }',
    '',
    '    const priced = priceLines(input.lines, (id) => this.#products.priceOf(id));',
    '    for (const line of priced) {',
    '      const reserved = await this.#products.reserveStock(line.productId, line.quantity);',
    '      if (!reserved) {',
    "        throw new Error('Sin existencias suficientes de ' + line.productId);",
    '      }',
    '    }',
    '',
    '    const totals = calculateTotals(priced);',
    '    const orderId = await this.#createOrder({',
    '      email: input.customer.email,',
    '      total: totals.total,',
    '    });',
    '    return { orderId, total: totals.total };',
    '  }',
    '}',
  ].join('\n');
}

function checkoutRoutes(): string {
  return [
    "import type { FastifyInstance } from 'fastify';",
    "import { CheckoutService, type CheckoutInput } from '../application/CheckoutService.ts';",
    '',
    'export async function registerCheckoutRoutes(app: FastifyInstance): Promise<void> {',
    '  // PENDIENTE: sustituir por el repositorio real de productos y pedidos.',
    '  const service = new CheckoutService(',
    '    {',
    '      priceOf: () => undefined,',
    '      reserveStock: async () => false,',
    '    },',
    "    async () => { throw new Error('Persistencia de pedidos no conectada'); },",
    '  );',
    '',
    "  app.post<{ Body: CheckoutInput }>('/api/checkout', async (request, reply) => {",
    '    try {',
    '      return await service.checkout(request.body);',
    '    } catch (error) {',
    '      return reply.code(400).send({ message: (error as Error).message });',
    '    }',
    '  });',
    '}',
  ].join('\n');
}
